import { useState } from "react";

import Navbar from "../components/Navbar";
import ReviewDialog from "../components/ReviewDialog";

import type { ApiMovieResponse } from "../types/ApiMovieResponse";
import type { ReviewResponse } from "../types/ReviewResponse";

import { searchMovies } from "../services/MovieService";
import {
  markMovieAsWatched,
  getWatchedMovies,
} from "../services/WatchedService";
import {
  addReview,
  getMyReviews,
  updateReview,
} from "../services/ReviewService";

import {
  Alert,
  Box,
  Button,
  CircularProgress,
  Container,
  Divider,
  Snackbar,
  TextField,
  Typography,
} from "@mui/material";

function SearchPage() {
  const [query, setQuery] = useState("");

  const [movies, setMovies] = useState<ApiMovieResponse[]>([]);

  const [loading, setLoading] = useState(false);

  const [showReviewModal, setShowReviewModal] = useState(false);

  const [selectedMovieId, setSelectedMovieId] = useState<number | null>(null);

  const [selectedMovieTitle, setSelectedMovieTitle] = useState<string | null>(
    null,
  );

  const [selectedReview, setSelectedReview] = useState<ReviewResponse | null>(
    null,
  );

  const [reviews, setReviews] = useState<ReviewResponse[]>([]);

  const [watchedMovieIds, setWatchedMovieIds] = useState<Set<number>>(
    new Set(),
  );

  const [snackbarOpen, setSnackbarOpen] = useState(false);

  const [snackbarMessage, setSnackbarMessage] = useState("");

  async function handleSearch() {
    if (query.trim() === "") {
      return;
    }

    setLoading(true);

    try {
      const [searchResponse, watchedResponse, reviewResponse] =
        await Promise.all([
          searchMovies(query),
          getWatchedMovies(),
          getMyReviews(),
        ]);

      setMovies(searchResponse);

      setWatchedMovieIds(
        new Set(watchedResponse.map((movie) => movie.apiMovieId)),
      );

      setReviews(reviewResponse);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  }

  async function handleWatched(movieId: number, movieTitle: string) {
    try {
      await markMovieAsWatched(movieId, movieTitle);

      setWatchedMovieIds((prev) => {
        const updated = new Set(prev);

        updated.add(movieId);

        return updated;
      });

      setSnackbarMessage("Movie marked as watched!");

      setSnackbarOpen(true);
    } catch (error) {
      console.error(error);
    }
  }

  async function handleReviewSubmit(rating: number, comment: string) {
    if (selectedMovieId == null || selectedMovieTitle == null) {
      return;
    }

    try {
      if (selectedReview == null) {
        await addReview(selectedMovieId, rating, comment, selectedMovieTitle);

        const newReview: ReviewResponse = {
          id: "12345", //This is placeholder, the actual ID will be generated by the backend.
          apiMovieId: selectedMovieId,
          movieTitle: selectedMovieTitle,
          rating,
          comment,
          createdAt: new Date().toISOString(),
        };

        setReviews((prev) => [...prev, newReview]);
      } else {
        await updateReview(
          selectedReview.id,
          rating,
          comment,
          selectedReview.movieTitle,
          selectedReview.apiMovieId,
        );

        setReviews((prev) =>
          prev.map((review) =>
            review.id === selectedReview.id
              ? {
                  ...review,
                  rating,
                  comment,
                }
              : review,
          ),
        );
      }

      setSnackbarMessage("Review saved successfully!");

      setSnackbarOpen(true);

      setSelectedReview(null);

      setShowReviewModal(false);
    } catch (error) {
      console.error(error);
    }
  }

  function handleReviewSkip() {
    setSelectedReview(null);

    setShowReviewModal(false);
  }
  return (
    <>
      <Navbar />

      <Container>
        <Box sx={{ mt: 4 }}>
          <Typography variant="h4">Search Movies</Typography>
        </Box>

        <Divider sx={{ my: 2 }} />

        <Box
          sx={{
            display: "flex",
            gap: 2,
            mb: 4,
          }}
        >
          <TextField
            fullWidth
            label="Search Movie"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
          />

          <Button variant="contained" onClick={handleSearch}>
            Search
          </Button>
        </Box>

        {loading ? (
          <Box
            sx={{
              display: "flex",
              justifyContent: "center",
              mt: 5,
            }}
          >
            <CircularProgress />
          </Box>
        ) : (
          movies.map((movie) => {
            const hasWatched = watchedMovieIds.has(movie.id);

            const existingReview = reviews.find(
              (review) => review.apiMovieId === movie.id,
            );

            return (
              <Box key={movie.id}>
                <Typography variant="h5">{movie.title}</Typography>

                <img src={movie.posterUrl} width="150" />

                <Typography sx={{ mt: 2 }}>{movie.overview}</Typography>

                <Box sx={{ mt: 2 }}>
                  {hasWatched ? (
                    <Button variant="contained" color="success" disabled>
                      ✓ Watched
                    </Button>
                  ) : (
                    <Button
                      variant="contained"
                      onClick={() => handleWatched(movie.id, movie.title)}
                    >
                      Mark Watched
                    </Button>
                  )}

                  {existingReview ? (
                    <Button
                      variant="outlined"
                      sx={{ ml: 2 }}
                      onClick={() => {
                        setSelectedMovieId(movie.id);

                        setSelectedMovieTitle(movie.title);

                        setSelectedReview(existingReview);

                        setShowReviewModal(true);
                      }}
                    >
                      Update Review
                    </Button>
                  ) : (
                    <Button
                      variant="outlined"
                      sx={{ ml: 2 }}
                      onClick={() => {
                        setSelectedMovieId(movie.id);

                        setSelectedMovieTitle(movie.title);

                        setSelectedReview(null);

                        setShowReviewModal(true);
                      }}
                    >
                      Review Movie
                    </Button>
                  )}
                </Box>

                <Divider sx={{ my: 3 }} />
              </Box>
            );
          })
        )}

        <ReviewDialog
          open={showReviewModal}
          title={selectedReview ? "Update Review" : "Review Movie"}
          initialRating={selectedReview?.rating}
          initialComment={selectedReview?.comment}
          onSubmit={handleReviewSubmit}
          onSkip={handleReviewSkip}
        />
      </Container>

      <Snackbar
        open={snackbarOpen}
        autoHideDuration={3000}
        onClose={() => setSnackbarOpen(false)}
      >
        <Alert severity="success" variant="filled">
          {snackbarMessage}
        </Alert>
      </Snackbar>
    </>
  );
}

export default SearchPage;
